# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 15:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageuser',
            name='PhoneNum',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number \n\t\tmust be entered in the format: 13588888888. Up to 11 digits allowed. ', regex='^\\d{11}$')]),
        ),
    ]
