# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 17:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0002_auto_20160415_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageuser',
            name='UpdateTime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 15, 17, 22, 52, 905758, tzinfo=utc), verbose_name='更新时间'),
            preserve_default=False,
        ),
    ]
